version: '3'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.10.6
    environment:
      - SERVICES=serverless,stepfunctions,sns,sqs,secretsmanager
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=serverlesshellonode_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock      
    ports:
      - "8080:8080"
      - "4567-4587:4567-4587"
      - "4592-4593:4592-4593"